### ISSUE TITLE
Unable to download manga

### ISSUE THREAD

**Issue by sam5558** [Harkame/JapScanDownloader#21]
Hello, 
Great piece of code you have here.
I've tried your script but got the following error : 
```python
python3 japscandownloader/main.py 
[                                                                            ] - [0/47] - [chapters]Traceback (most recent call last):
  File "japscandownloader/main.py", line 17, in <module>
    main(sys.argv[1:])
  File "japscandownloader/main.py", line 14, in main
    download_manga(scraper, manga)
  File "/home/zen/Téléchargements/JapScanDownloader/japscandownloader/helpers/download_helper.py", line 50, in download_manga
    download_chapter(scraper, manga['chapters']['url'] + str(base_counter) + "/")
  File "/home/zen/Téléchargements/JapScanDownloader/japscandownloader/helpers/download_helper.py", line 60, in download_chapter
    pages = BeautifulSoup(scraper.get(chapter_url).content, features='lxml').find('select', {'id': 'pages'})
  File "/home/zen/.local/lib/python3.6/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/home/zen/.local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 154, in request
    resp = self.sendChallengeResponse(resp, **kwargs)
  File "/home/zen/.local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 236, in sendChallengeResponse
    return self.request(resp.request.method, redirect_url, **original_kwargs)
  File "/home/zen/.local/lib/python3.6/site-packages/cloudscraper/__init__.py", line 136, in request
    resp._content = brotli.decompress(resp.content)
brotli.error: BrotliDecompress failed
```
I've used the following config.yml : 
```yaml
mangas:
#  - chapter:
#      https://www.japscan.to/lecture-en-ligne/shingeki-no-kyojin/116/

#  - url:
#      https://www.japscan.to/manga/uq-holder/

  - chapters:
      url:
         https://www.japscan.to/lecture-en-ligne/blue-giant/
      chapter_min:
         1
      chapter_max:
         48

destination_path:
  /home/zen/Téléchargements/JapScanDownloader

manga_format:
  cbz

```

For the tox part it's giving me : 
```shell
GLOB sdist-make: /home/zen/Téléchargements/JapScanDownloader/setup.py
py34 create: /home/zen/Téléchargements/JapScanDownloader/.tox/py34
ERROR: InterpreterNotFound: python3.4
py35 create: /home/zen/Téléchargements/JapScanDownloader/.tox/py35
ERROR: InterpreterNotFound: python3.5
py36 create: /home/zen/Téléchargements/JapScanDownloader/.tox/py36
py36 installdeps: pytest, pytest-cov, numpy, pillow, -rrequirements.txt
py36 inst: /home/zen/Téléchargements/JapScanDownloader/.tox/.tmp/package/1/japscandownloader-0.0.1.zip
py36 installed: asn1crypto==0.24.0,atomicwrites==1.3.0,attrs==19.1.0,beautifulsoup4==4.7.1,Brotli==1.0.7,certifi==2019.3.9,cffi==1.12.3,chardet==3.0.4,cloudscraper==1.1.11,coverage==4.5.3,cryptography==2.6.1,idna==2.8,japscandownloader==0.0.1,Js2Py==0.63,lxml==4.3.3,more-itertools==7.0.0,numpy==1.16.3,Pillow==6.0.0,pluggy==0.11.0,py==1.8.0,pycparser==2.19,pyjsparser==2.7.1,pyOpenSSL==19.0.0,pytest==4.5.0,pytest-cov==2.7.1,pytz==2019.1,PyYAML==5.1,requests==2.22.0,requests-toolbelt==0.9.1,six==1.12.0,soupsieve==1.9.1,tqdm==4.32.1,tzlocal==1.5.1,urllib3==1.25.3,wcwidth==0.1.7
py36 run-test-pre: PYTHONHASHSEED='278329458'
py36 run-test: commands[0] | pytest tests/test.py -q --cov=.
............                                                                                 [100%]

----------- coverage: platform linux, python 3.6.7-final-0 -----------
Name                           Stmts   Miss  Cover
--------------------------------------------------
__init__.py                        0      0   100%
helpers/__init__.py                0      0   100%
helpers/argument_helper.py        12      0   100%
helpers/config_helper.py           6      0   100%
helpers/download_helper.py        97     86    11%
helpers/format_helper.py          21      0   100%
helpers/unscramble_helper.py      39     12    69%
main.py                           11     11     0%
settings/__init__.py               0      0   100%
settings/settings.py              70     44    37%
tests/__init__.py                  0      0   100%
tests/test.py                    118      8    93%
--------------------------------------------------
TOTAL                            374    161    57%

12 passed in 5.19 seconds
py37 create: /home/zen/Téléchargements/JapScanDownloader/.tox/py37
ERROR: InterpreterNotFound: python3.7
_____________________________________________ summary ______________________________________________
ERROR:  py34: InterpreterNotFound: python3.4
ERROR:  py35: InterpreterNotFound: python3.5
  py36: commands succeeded
ERROR:  py37: InterpreterNotFound: python3.7

```
Any ideas why it's not working for me ?
Thanks

**Comment by Harkame** [comment]
Hi, thanks for your feedback !

I have found the problem,

The new version of package urllib3==1.25.3 send this error, you need to use an older version, for me version urllib3==1.24.3 is ok

You can replace this version with command pip install urllib3==1.24.3.

I have updated requirements.txt so you can also reinstall packages with pip install -r requierements.txt

Just make sure you have package urllib3==1.24.3 with command : pip freeze

**Comment by sam5558** [comment]
Thank you ! 
It worked :) 
I've been working myself on a small python script that was working before (deprecated now hehe).
But i wanted to thank you because this script does what we want from his and he does it right :+1:
