### ISSUE TITLE
 [Errno 2] No such file or directory: './config.yml'

### ISSUE THREAD

**Issue by sangorys** [Harkame/JapScanDownloader#55]
**Context :**

I have done :
**pip3 install --user --use-feature=2020-resolver japscandownloader
japscandownloader**

**Answer :**
Traceback (most recent call last):
  File "/home/sangorys/.local/bin/japscandownloader", line 8, in <module>
    sys.exit(main())
  File "/home/sangorys/.local/lib/python3.8/site-packages/japscandownloader/main.py", line 8, in main
    jsd.init(sys.argv[1:])
  File "/home/sangorys/.local/lib/python3.8/site-packages/japscandownloader/jsd_selenium.py", line 59, in init
    self.init_config()
  File "/home/sangorys/.local/lib/python3.8/site-packages/japscandownloader/jsd_selenium.py", line 146, in init_config
    config = get_config(self.config_file)
  File "/home/sangorys/.local/lib/python3.8/site-packages/japscandownloader/helpers/helper_config.py", line 9, in get_config
    config_file = open(config_file_path, "r")
FileNotFoundError: [Errno 2] **No such file or directory**: './config.yml'

However, when I do :
**ls**
build  config.yml  CONTRIBUTING.md  dist  japscandownloader  japscandownloader.egg-info  LICENSE  Pipfile  Pipfile.lock  README.md  setup.py  tools

Please help

**Comment by Harkame** [comment]
Hi, you need to execute the command 
``` bash
japscandownloader
```
in a folder that contain a file named « config.yml », there is an example here https://github.com/Harkame/JapScanDownloader/blob/master/config.yml
