### ISSUE TITLE
Error on download

### ISSUE THREAD

**Issue by Systemac** [Harkame/JapScanDownloader#73]
First, thank's to your job, very useful !

So I just have this error : 

$ japscandownloader
[                                                                                         ] - [0/9] - [chapters: https://www.japscan.lol/manga/gunnm/]Traceback (most recent call last):                                                                                                ] - [0/246] - [pages]
  File "E:\Python39\Scripts\japscandownloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('japscandownloader==1.0.9', 'console_scripts', 'japscandownloader')())
  File "E:\Python39\lib\site-packages\japscandownloader\main.py", line 11, in main
    jsd.download(manga)
  File "E:\Python39\lib\site-packages\japscandownloader\jsd_selenium.py", line 237, in download
    self.download_chapter(chapter["url"])
  File "E:\Python39\lib\site-packages\japscandownloader\jsd_selenium.py", line 339, in download_chapter
    file = self.download_page(chapter_path, page_url, index, len(page_options))
  File "E:\Python39\lib\site-packages\japscandownloader\jsd_selenium.py", line 452, in download_page
    raise RuntimeError("unable to get image " + src)
RuntimeError: unable to get image https://c.japscan.lol/7158f2e8c368a831112864f8399109810138e3e8d668097162c8d49872a820f87248c10174b84091f3085061283836b/8a23873086818859869881168b6a17288237879483071b4a8c018d658283886e1ex887011a732f0e25992e611cy01c2/61e4e168d28z186281c5826ua10y07b648a5d88zf704c8bxe720a9dx6960e08wf97z59f1e0cz67ax391y296yf930900/2890z37.jpg

and if I try to go on this url, I found that :

![image](https://user-images.githubusercontent.com/7353752/229610901-57339dcd-61a6-46fa-a126-d45f9bb45097.png)

**Comment by Systemac** [comment]
Hello, thank's for you work, but this is the same error :

RuntimeError: unable to get image https://c.japscan.lol/7158f2e8c368a831112864f8399109810138e3e8d668097162c8d49872a820f87248c10174b84091f3085061283836b/8a23873086818859869881168b6a17288237879483071b4a8c018d658283886e1ex887011a732f0e25992e611cy01c2/61e4e168d28z186281c5826ua10y07b648a5d88zf704c8bxe720a9dx6960e08wf97z59f1e0cz67ax391y296yf930900/2890z37.jpg
